### ISSUE TITLE
issue with images generated in loop, all end referencing the same bookmark

### ISSUE THREAD

**Issue by bengiexd** [jsreport/jsreport-docx#17]
Hi.
I am trying to put together an image table, each row has two images, I am having problems if I only use two base hyperlinks on which I generate the table rows.
thanks.

**Comment by bjrmatos** [comment]
hi! it should be possible to create a table with many images, to understand better your problem I think it will be great if you share the template you are using, so I can check what are you doing. you can share in the [playground](https://playground.jsreport.net/) or as an [export zip](https://jsreport.net/learn/import-export) if you want

**Comment by bengiexd** [comment]
Hi. #
I share the template with you.
https://drive.google.com/file/d/1oq1Nt4BJP6mit3XZCNRfLyWn41smP-4d/view?usp=sharing

data = {
     rows: [
              {type_2p: true, title: 'title 1', uri1: '', uri2: ''},
              {type_2p: true, title: 'title 2', uri1: '', uri2: ''},
              {type_2p: true, title: 'title 3', uri1: '', uri2: ''}
     ]
}
uri1 and uri2 are images valid in base64.

the problem is that a hyperlink is created in each image and when you press it it goes to the lowest part of the document (ctrl + click or by chance), with many pages the error is very serious, check the jsreport-docx code, and temporarily modify
node_modules/jsreport-docx/lib/scriptDocxProcessing.js line 64
if (f.path === 'word / document.xml') {
     f.data = f.data.replace (/ <a: hlinkClick. *? \ /> / g, '')
}
and everything works great.

**Comment by bjrmatos** [comment]
sorry for the delay and thanks for sharing the docx template.

just for reference here are the steps to create an image and be able to replace it at runtime
>Select image, select Word tab "Insert", click on "Bookmark and create one
Right click image and click "Hyperlink"
Click bookmark and select previously created bookmark

the image should be always linked to a bookmark, so the issue here is that any image generated in the handlebars each loop references to the same bookmark so if you generate for example 5 images in the loop, the 5 images we will redirect you to the same bookmark, which is incorrect, we need to fix this and correctly update the bookmark per each image generated.

now just a comment about your template, it seems that you also created bookmarks for the 3 images you have in the docx, however, when inspecting the docx, i don't see the bookmarks defined or its locations in the docx, which is weird. and also it seems that MS word just takes you to the beginning of the document if you click a bookmark that does not exist.

**Comment by bengiexd** [comment]
Hi @bjrmatos 
Thanks for the answer.
I will check my template one more time in case I did something wrong when adding the images, try to follow the steps of https://jsreport.net/learn/docx#docximage

**Comment by bjrmatos** [comment]
this should be fixed now
